version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fin_aggregator_user
      POSTGRES_DB: fin_aggregator_db
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fin_aggregator_user -d fin_aggregator_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=fin_aggregator_user
      - DB_NAME=fin_aggregator_db
    volumes:
      - ./logs:/app/logs
      - ./config/config.yaml:/config/config.yaml
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data: