// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/fin-aggregate-service/fin-aggregate-service.proto

package fin_aggregator_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_UNSPECIFIED TransactionType = 0
	TransactionType_INCOME      TransactionType = 1
	TransactionType_OUTCOME     TransactionType = 2
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INCOME",
		2: "OUTCOME",
	}
	TransactionType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"INCOME":      1,
		"OUTCOME":     2,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_api_fin_aggregate_service_fin_aggregate_service_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{0}
}

type BankImportMethod int32

const (
	BankImportMethod_UNDEFINED BankImportMethod = 0
	BankImportMethod_CSV       BankImportMethod = 1
	BankImportMethod_API       BankImportMethod = 2
)

// Enum value maps for BankImportMethod.
var (
	BankImportMethod_name = map[int32]string{
		0: "UNDEFINED",
		1: "CSV",
		2: "API",
	}
	BankImportMethod_value = map[string]int32{
		"UNDEFINED": 0,
		"CSV":       1,
		"API":       2,
	}
)

func (x BankImportMethod) Enum() *BankImportMethod {
	p := new(BankImportMethod)
	*p = x
	return p
}

func (x BankImportMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankImportMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_enumTypes[1].Descriptor()
}

func (BankImportMethod) Type() protoreflect.EnumType {
	return &file_api_fin_aggregate_service_fin_aggregate_service_proto_enumTypes[1]
}

func (x BankImportMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankImportMethod.Descriptor instead.
func (BankImportMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{1}
}

type Transaction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BankId          int64                  `protobuf:"varint,2,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	ExternalId      string                 `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	UserId          int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"`
	Amount          string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	CategoryId      int64                  `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Type            TransactionType        `protobuf:"varint,9,opt,name=type,proto3,enum=fin_aggregator_service.TransactionType" json:"type,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	BankName        string                 `protobuf:"bytes,11,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	CategoryName    string                 `protobuf:"bytes,12,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	UserName        string                 `protobuf:"bytes,13,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *Transaction) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Transaction) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Transaction) GetTransactionDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionDate
	}
	return nil
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_UNSPECIFIED
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *Transaction) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Transaction) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         int32                  `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BankId        int64                  `protobuf:"varint,4,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *GetTransactionsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetTransactionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetTransactionsRequest) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	TotalIncome   string                 `protobuf:"bytes,3,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalOutcome  string                 `protobuf:"bytes,4,opt,name=total_outcome,json=totalOutcome,proto3" json:"total_outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetTransactionsResponse) GetTotalIncome() string {
	if x != nil {
		return x.TotalIncome
	}
	return ""
}

func (x *GetTransactionsResponse) GetTotalOutcome() string {
	if x != nil {
		return x.TotalOutcome
	}
	return ""
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CategoryId    *int64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Type          *TransactionType       `protobuf:"varint,3,opt,name=type,proto3,enum=fin_aggregator_service.TransactionType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTransactionRequest) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetType() TransactionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TransactionType_UNSPECIFIED
}

type UpdateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionResponse) Reset() {
	*x = UpdateTransactionResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionResponse) ProtoMessage() {}

func (x *UpdateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type MonzoCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonzoCallbackRequest) Reset() {
	*x = MonzoCallbackRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonzoCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonzoCallbackRequest) ProtoMessage() {}

func (x *MonzoCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonzoCallbackRequest.ProtoReflect.Descriptor instead.
func (*MonzoCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{5}
}

func (x *MonzoCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MonzoCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type MonzoCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonzoCallbackResponse) Reset() {
	*x = MonzoCallbackResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonzoCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonzoCallbackResponse) ProtoMessage() {}

func (x *MonzoCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonzoCallbackResponse.ProtoReflect.Descriptor instead.
func (*MonzoCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{6}
}

func (x *MonzoCallbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MonzoAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonzoAccountRequest) Reset() {
	*x = MonzoAccountRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonzoAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonzoAccountRequest) ProtoMessage() {}

func (x *MonzoAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonzoAccountRequest.ProtoReflect.Descriptor instead.
func (*MonzoAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{7}
}

type MonzoAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonzoAccountResponse) Reset() {
	*x = MonzoAccountResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonzoAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonzoAccountResponse) ProtoMessage() {}

func (x *MonzoAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonzoAccountResponse.ProtoReflect.Descriptor instead.
func (*MonzoAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{8}
}

func (x *MonzoAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMonzoAuthURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonzoAuthURLRequest) Reset() {
	*x = GetMonzoAuthURLRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonzoAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonzoAuthURLRequest) ProtoMessage() {}

func (x *GetMonzoAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonzoAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetMonzoAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{9}
}

type GetMonzoAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonzoAuthURLResponse) Reset() {
	*x = GetMonzoAuthURLResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonzoAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonzoAuthURLResponse) ProtoMessage() {}

func (x *GetMonzoAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonzoAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetMonzoAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetMonzoAuthURLResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

type LoadMonzoTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=since,proto3" json:"since,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BankId        int64                  `protobuf:"varint,4,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMonzoTransactionsRequest) Reset() {
	*x = LoadMonzoTransactionsRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMonzoTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMonzoTransactionsRequest) ProtoMessage() {}

func (x *LoadMonzoTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMonzoTransactionsRequest.ProtoReflect.Descriptor instead.
func (*LoadMonzoTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{11}
}

func (x *LoadMonzoTransactionsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *LoadMonzoTransactionsRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *LoadMonzoTransactionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoadMonzoTransactionsRequest) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

type LoadMonzoTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMonzoTransactionsResponse) Reset() {
	*x = LoadMonzoTransactionsResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMonzoTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMonzoTransactionsResponse) ProtoMessage() {}

func (x *LoadMonzoTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMonzoTransactionsResponse.ProtoReflect.Descriptor instead.
func (*LoadMonzoTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{12}
}

func (x *LoadMonzoTransactionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadCSVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvData       []byte                 `protobuf:"bytes,1,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	BankId        int64                  `protobuf:"varint,3,opt,name=bank_id,json=bankId,proto3" json:"bank_id,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCSVRequest) Reset() {
	*x = UploadCSVRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCSVRequest) ProtoMessage() {}

func (x *UploadCSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCSVRequest.ProtoReflect.Descriptor instead.
func (*UploadCSVRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{13}
}

func (x *UploadCSVRequest) GetCsvData() []byte {
	if x != nil {
		return x.CsvData
	}
	return nil
}

func (x *UploadCSVRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadCSVRequest) GetBankId() int64 {
	if x != nil {
		return x.BankId
	}
	return 0
}

func (x *UploadCSVRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UploadCSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RecordError   []*RecordError         `protobuf:"bytes,2,rep,name=record_error,json=recordError,proto3" json:"record_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadCSVResponse) Reset() {
	*x = UploadCSVResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadCSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadCSVResponse) ProtoMessage() {}

func (x *UploadCSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadCSVResponse.ProtoReflect.Descriptor instead.
func (*UploadCSVResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{14}
}

func (x *UploadCSVResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadCSVResponse) GetRecordError() []*RecordError {
	if x != nil {
		return x.RecordError
	}
	return nil
}

type RecordError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowId         int64                  `protobuf:"varint,1,opt,name=row_id,json=rowId,proto3" json:"row_id,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordError) Reset() {
	*x = RecordError{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordError) ProtoMessage() {}

func (x *RecordError) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordError.ProtoReflect.Descriptor instead.
func (*RecordError) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{15}
}

func (x *RecordError) GetRowId() int64 {
	if x != nil {
		return x.RowId
	}
	return 0
}

func (x *RecordError) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ListBankRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankRequest) Reset() {
	*x = ListBankRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankRequest) ProtoMessage() {}

func (x *ListBankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankRequest.ProtoReflect.Descriptor instead.
func (*ListBankRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{16}
}

type ListBankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banks         []*Bank                `protobuf:"bytes,1,rep,name=banks,proto3" json:"banks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBankResponse) Reset() {
	*x = ListBankResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBankResponse) ProtoMessage() {}

func (x *ListBankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBankResponse.ProtoReflect.Descriptor instead.
func (*ListBankResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListBankResponse) GetBanks() []*Bank {
	if x != nil {
		return x.Banks
	}
	return nil
}

type Bank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImportMethod  BankImportMethod       `protobuf:"varint,3,opt,name=import_method,json=importMethod,proto3,enum=fin_aggregator_service.BankImportMethod" json:"import_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bank) Reset() {
	*x = Bank{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank) ProtoMessage() {}

func (x *Bank) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank.ProtoReflect.Descriptor instead.
func (*Bank) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{18}
}

func (x *Bank) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bank) GetImportMethod() BankImportMethod {
	if x != nil {
		return x.ImportMethod
	}
	return BankImportMethod_UNDEFINED
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{19}
}

type ListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Banks         []int64                `protobuf:"varint,3,rep,packed,name=banks,proto3" json:"banks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{21}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetBanks() []int64 {
	if x != nil {
		return x.Banks
	}
	return nil
}

type ListCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryRequest) Reset() {
	*x = ListCategoryRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryRequest) ProtoMessage() {}

func (x *ListCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{22}
}

type ListCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      []*Category            `protobuf:"bytes,1,rep,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoryResponse) Reset() {
	*x = ListCategoryResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoryResponse) ProtoMessage() {}

func (x *ListCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoryResponse.ProtoReflect.Descriptor instead.
func (*ListCategoryResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListCategoryResponse) GetCategory() []*Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{24}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTransactionTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionTypeRequest) Reset() {
	*x = ListTransactionTypeRequest{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionTypeRequest) ProtoMessage() {}

func (x *ListTransactionTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionTypeRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{25}
}

type ListTransactionTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          []TransactionType      `protobuf:"varint,1,rep,packed,name=type,proto3,enum=fin_aggregator_service.TransactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionTypeResponse) Reset() {
	*x = ListTransactionTypeResponse{}
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionTypeResponse) ProtoMessage() {}

func (x *ListTransactionTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionTypeResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionTypeResponse) Descriptor() ([]byte, []int) {
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListTransactionTypeResponse) GetType() []TransactionType {
	if x != nil {
		return x.Type
	}
	return nil
}

var File_api_fin_aggregate_service_fin_aggregate_service_proto protoreflect.FileDescriptor

const file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDesc = "" +
	"\n" +
	"5api/fin-aggregate-service/fin-aggregate-service.proto\x12\x16fin_aggregator_service\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x03\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\abank_id\x18\x02 \x01(\x03R\x06bankId\x12\x1f\n" +
	"\vexternal_id\x18\x03 \x01(\tR\n" +
	"externalId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12E\n" +
	"\x10transaction_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionDate\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x03R\n" +
	"categoryId\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12;\n" +
	"\x04type\x18\t \x01(\x0e2'.fin_aggregator_service.TransactionTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tbank_name\x18\v \x01(\tR\bbankName\x12#\n" +
	"\rcategory_name\x18\f \x01(\tR\fcategoryName\x12\x1b\n" +
	"\tuser_name\x18\r \x01(\tR\buserName\"t\n" +
	"\x16GetTransactionsRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\x05R\x05month\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x17\n" +
	"\abank_id\x18\x04 \x01(\x03R\x06bankId\"\xcb\x01\n" +
	"\x17GetTransactionsResponse\x12G\n" +
	"\ftransactions\x18\x01 \x03(\v2#.fin_aggregator_service.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\ftotal_income\x18\x03 \x01(\tR\vtotalIncome\x12#\n" +
	"\rtotal_outcome\x18\x04 \x01(\tR\ftotalOutcome\"\xc2\x01\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12@\n" +
	"\x04type\x18\x03 \x01(\x0e2'.fin_aggregator_service.TransactionTypeH\x01R\x04type\x88\x01\x01B\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_type\"b\n" +
	"\x19UpdateTransactionResponse\x12E\n" +
	"\vtransaction\x18\x01 \x01(\v2#.fin_aggregator_service.TransactionR\vtransaction\"@\n" +
	"\x14MonzoCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"1\n" +
	"\x15MonzoCallbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13MonzoAccountRequest\"0\n" +
	"\x14MonzoAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16GetMonzoAuthURLRequest\"4\n" +
	"\x17GetMonzoAuthURLResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\"\xb6\x01\n" +
	"\x1cLoadMonzoTransactionsRequest\x120\n" +
	"\x05since\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x122\n" +
	"\x06before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x17\n" +
	"\abank_id\x18\x04 \x01(\x03R\x06bankId\"9\n" +
	"\x1dLoadMonzoTransactionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"{\n" +
	"\x10UploadCSVRequest\x12\x19\n" +
	"\bcsv_data\x18\x01 \x01(\fR\acsvData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x17\n" +
	"\abank_id\x18\x03 \x01(\x03R\x06bankId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"u\n" +
	"\x11UploadCSVResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12F\n" +
	"\frecord_error\x18\x02 \x03(\v2#.fin_aggregator_service.RecordErrorR\vrecordError\"<\n" +
	"\vRecordError\x12\x15\n" +
	"\x06row_id\x18\x01 \x01(\x03R\x05rowId\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"\x11\n" +
	"\x0fListBankRequest\"F\n" +
	"\x10ListBankResponse\x122\n" +
	"\x05banks\x18\x01 \x03(\v2\x1c.fin_aggregator_service.BankR\x05banks\"y\n" +
	"\x04Bank\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12M\n" +
	"\rimport_method\x18\x03 \x01(\x0e2(.fin_aggregator_service.BankImportMethodR\fimportMethod\"\x11\n" +
	"\x0fListUserRequest\"F\n" +
	"\x10ListUserResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.fin_aggregator_service.UserR\x05users\"@\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05banks\x18\x03 \x03(\x03R\x05banks\"\x15\n" +
	"\x13ListCategoryRequest\"T\n" +
	"\x14ListCategoryResponse\x12<\n" +
	"\bcategory\x18\x01 \x03(\v2 .fin_aggregator_service.CategoryR\bcategory\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1c\n" +
	"\x1aListTransactionTypeRequest\"Z\n" +
	"\x1bListTransactionTypeResponse\x12;\n" +
	"\x04type\x18\x01 \x03(\x0e2'.fin_aggregator_service.TransactionTypeR\x04type*;\n" +
	"\x0fTransactionType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06INCOME\x10\x01\x12\v\n" +
	"\aOUTCOME\x10\x02*3\n" +
	"\x10BankImportMethod\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\a\n" +
	"\x03CSV\x10\x01\x12\a\n" +
	"\x03API\x10\x022\xfe\v\n" +
	"\x14FinAggregatorService\x12\x89\x01\n" +
	"\x0fGetTransactions\x12..fin_aggregator_service.GetTransactionsRequest\x1a/.fin_aggregator_service.GetTransactionsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/transactions\x12\xa3\x01\n" +
	"\x11UpdateTransaction\x120.fin_aggregator_service.UpdateTransactionRequest\x1a1.fin_aggregator_service.UpdateTransactionResponse\")\x82\xd3\xe4\x93\x02#:\x01*2\x1e/transactions/{transaction_id}\x12\x8b\x01\n" +
	"\x0fGetMonzoAuthURL\x12..fin_aggregator_service.GetMonzoAuthURLRequest\x1a/.fin_aggregator_service.GetMonzoAuthURLResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/monzo/auth-url\x12\x85\x01\n" +
	"\rMonzoCallback\x12,.fin_aggregator_service.MonzoCallbackRequest\x1a-.fin_aggregator_service.MonzoCallbackResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/monzo/callback\x12\x84\x01\n" +
	"\x0fGetMonzoAccount\x12+.fin_aggregator_service.MonzoAccountRequest\x1a,.fin_aggregator_service.MonzoAccountResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/monzo/account\x12\xa1\x01\n" +
	"\x15LoadMonzoTransactions\x124.fin_aggregator_service.LoadMonzoTransactionsRequest\x1a5.fin_aggregator_service.LoadMonzoTransactionsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/monzo/transactions\x12x\n" +
	"\tUploadCSV\x12(.fin_aggregator_service.UploadCSVRequest\x1a).fin_aggregator_service.UploadCSVResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/upload-csv\x12m\n" +
	"\bListBank\x12'.fin_aggregator_service.ListBankRequest\x1a(.fin_aggregator_service.ListBankResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/banks\x12m\n" +
	"\bListUser\x12'.fin_aggregator_service.ListUserRequest\x1a(.fin_aggregator_service.ListUserResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/users\x12~\n" +
	"\fListCategory\x12+.fin_aggregator_service.ListCategoryRequest\x1a,.fin_aggregator_service.ListCategoryResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/categories\x12\x9a\x01\n" +
	"\x13ListTransactionType\x122.fin_aggregator_service.ListTransactionTypeRequest\x1a3.fin_aggregator_service.ListTransactionTypeResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/transaction-typesBLZJgithub.com/handmade-jewelry/user/pkg/fin-aggregator;fin_aggregator_serviceb\x06proto3"

var (
	file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescOnce sync.Once
	file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescData []byte
)

func file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescGZIP() []byte {
	file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescOnce.Do(func() {
		file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDesc), len(file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDesc)))
	})
	return file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDescData
}

var file_api_fin_aggregate_service_fin_aggregate_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_api_fin_aggregate_service_fin_aggregate_service_proto_goTypes = []any{
	(TransactionType)(0),                  // 0: fin_aggregator_service.TransactionType
	(BankImportMethod)(0),                 // 1: fin_aggregator_service.BankImportMethod
	(*Transaction)(nil),                   // 2: fin_aggregator_service.Transaction
	(*GetTransactionsRequest)(nil),        // 3: fin_aggregator_service.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),       // 4: fin_aggregator_service.GetTransactionsResponse
	(*UpdateTransactionRequest)(nil),      // 5: fin_aggregator_service.UpdateTransactionRequest
	(*UpdateTransactionResponse)(nil),     // 6: fin_aggregator_service.UpdateTransactionResponse
	(*MonzoCallbackRequest)(nil),          // 7: fin_aggregator_service.MonzoCallbackRequest
	(*MonzoCallbackResponse)(nil),         // 8: fin_aggregator_service.MonzoCallbackResponse
	(*MonzoAccountRequest)(nil),           // 9: fin_aggregator_service.MonzoAccountRequest
	(*MonzoAccountResponse)(nil),          // 10: fin_aggregator_service.MonzoAccountResponse
	(*GetMonzoAuthURLRequest)(nil),        // 11: fin_aggregator_service.GetMonzoAuthURLRequest
	(*GetMonzoAuthURLResponse)(nil),       // 12: fin_aggregator_service.GetMonzoAuthURLResponse
	(*LoadMonzoTransactionsRequest)(nil),  // 13: fin_aggregator_service.LoadMonzoTransactionsRequest
	(*LoadMonzoTransactionsResponse)(nil), // 14: fin_aggregator_service.LoadMonzoTransactionsResponse
	(*UploadCSVRequest)(nil),              // 15: fin_aggregator_service.UploadCSVRequest
	(*UploadCSVResponse)(nil),             // 16: fin_aggregator_service.UploadCSVResponse
	(*RecordError)(nil),                   // 17: fin_aggregator_service.RecordError
	(*ListBankRequest)(nil),               // 18: fin_aggregator_service.ListBankRequest
	(*ListBankResponse)(nil),              // 19: fin_aggregator_service.ListBankResponse
	(*Bank)(nil),                          // 20: fin_aggregator_service.Bank
	(*ListUserRequest)(nil),               // 21: fin_aggregator_service.ListUserRequest
	(*ListUserResponse)(nil),              // 22: fin_aggregator_service.ListUserResponse
	(*User)(nil),                          // 23: fin_aggregator_service.User
	(*ListCategoryRequest)(nil),           // 24: fin_aggregator_service.ListCategoryRequest
	(*ListCategoryResponse)(nil),          // 25: fin_aggregator_service.ListCategoryResponse
	(*Category)(nil),                      // 26: fin_aggregator_service.Category
	(*ListTransactionTypeRequest)(nil),    // 27: fin_aggregator_service.ListTransactionTypeRequest
	(*ListTransactionTypeResponse)(nil),   // 28: fin_aggregator_service.ListTransactionTypeResponse
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_api_fin_aggregate_service_fin_aggregate_service_proto_depIdxs = []int32{
	29, // 0: fin_aggregator_service.Transaction.transaction_date:type_name -> google.protobuf.Timestamp
	0,  // 1: fin_aggregator_service.Transaction.type:type_name -> fin_aggregator_service.TransactionType
	29, // 2: fin_aggregator_service.Transaction.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: fin_aggregator_service.GetTransactionsResponse.transactions:type_name -> fin_aggregator_service.Transaction
	0,  // 4: fin_aggregator_service.UpdateTransactionRequest.type:type_name -> fin_aggregator_service.TransactionType
	2,  // 5: fin_aggregator_service.UpdateTransactionResponse.transaction:type_name -> fin_aggregator_service.Transaction
	29, // 6: fin_aggregator_service.LoadMonzoTransactionsRequest.since:type_name -> google.protobuf.Timestamp
	29, // 7: fin_aggregator_service.LoadMonzoTransactionsRequest.before:type_name -> google.protobuf.Timestamp
	17, // 8: fin_aggregator_service.UploadCSVResponse.record_error:type_name -> fin_aggregator_service.RecordError
	20, // 9: fin_aggregator_service.ListBankResponse.banks:type_name -> fin_aggregator_service.Bank
	1,  // 10: fin_aggregator_service.Bank.import_method:type_name -> fin_aggregator_service.BankImportMethod
	23, // 11: fin_aggregator_service.ListUserResponse.users:type_name -> fin_aggregator_service.User
	26, // 12: fin_aggregator_service.ListCategoryResponse.category:type_name -> fin_aggregator_service.Category
	0,  // 13: fin_aggregator_service.ListTransactionTypeResponse.type:type_name -> fin_aggregator_service.TransactionType
	3,  // 14: fin_aggregator_service.FinAggregatorService.GetTransactions:input_type -> fin_aggregator_service.GetTransactionsRequest
	5,  // 15: fin_aggregator_service.FinAggregatorService.UpdateTransaction:input_type -> fin_aggregator_service.UpdateTransactionRequest
	11, // 16: fin_aggregator_service.FinAggregatorService.GetMonzoAuthURL:input_type -> fin_aggregator_service.GetMonzoAuthURLRequest
	7,  // 17: fin_aggregator_service.FinAggregatorService.MonzoCallback:input_type -> fin_aggregator_service.MonzoCallbackRequest
	9,  // 18: fin_aggregator_service.FinAggregatorService.GetMonzoAccount:input_type -> fin_aggregator_service.MonzoAccountRequest
	13, // 19: fin_aggregator_service.FinAggregatorService.LoadMonzoTransactions:input_type -> fin_aggregator_service.LoadMonzoTransactionsRequest
	15, // 20: fin_aggregator_service.FinAggregatorService.UploadCSV:input_type -> fin_aggregator_service.UploadCSVRequest
	18, // 21: fin_aggregator_service.FinAggregatorService.ListBank:input_type -> fin_aggregator_service.ListBankRequest
	21, // 22: fin_aggregator_service.FinAggregatorService.ListUser:input_type -> fin_aggregator_service.ListUserRequest
	24, // 23: fin_aggregator_service.FinAggregatorService.ListCategory:input_type -> fin_aggregator_service.ListCategoryRequest
	27, // 24: fin_aggregator_service.FinAggregatorService.ListTransactionType:input_type -> fin_aggregator_service.ListTransactionTypeRequest
	4,  // 25: fin_aggregator_service.FinAggregatorService.GetTransactions:output_type -> fin_aggregator_service.GetTransactionsResponse
	6,  // 26: fin_aggregator_service.FinAggregatorService.UpdateTransaction:output_type -> fin_aggregator_service.UpdateTransactionResponse
	12, // 27: fin_aggregator_service.FinAggregatorService.GetMonzoAuthURL:output_type -> fin_aggregator_service.GetMonzoAuthURLResponse
	8,  // 28: fin_aggregator_service.FinAggregatorService.MonzoCallback:output_type -> fin_aggregator_service.MonzoCallbackResponse
	10, // 29: fin_aggregator_service.FinAggregatorService.GetMonzoAccount:output_type -> fin_aggregator_service.MonzoAccountResponse
	14, // 30: fin_aggregator_service.FinAggregatorService.LoadMonzoTransactions:output_type -> fin_aggregator_service.LoadMonzoTransactionsResponse
	16, // 31: fin_aggregator_service.FinAggregatorService.UploadCSV:output_type -> fin_aggregator_service.UploadCSVResponse
	19, // 32: fin_aggregator_service.FinAggregatorService.ListBank:output_type -> fin_aggregator_service.ListBankResponse
	22, // 33: fin_aggregator_service.FinAggregatorService.ListUser:output_type -> fin_aggregator_service.ListUserResponse
	25, // 34: fin_aggregator_service.FinAggregatorService.ListCategory:output_type -> fin_aggregator_service.ListCategoryResponse
	28, // 35: fin_aggregator_service.FinAggregatorService.ListTransactionType:output_type -> fin_aggregator_service.ListTransactionTypeResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_fin_aggregate_service_fin_aggregate_service_proto_init() }
func file_api_fin_aggregate_service_fin_aggregate_service_proto_init() {
	if File_api_fin_aggregate_service_fin_aggregate_service_proto != nil {
		return
	}
	file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDesc), len(file_api_fin_aggregate_service_fin_aggregate_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_fin_aggregate_service_fin_aggregate_service_proto_goTypes,
		DependencyIndexes: file_api_fin_aggregate_service_fin_aggregate_service_proto_depIdxs,
		EnumInfos:         file_api_fin_aggregate_service_fin_aggregate_service_proto_enumTypes,
		MessageInfos:      file_api_fin_aggregate_service_fin_aggregate_service_proto_msgTypes,
	}.Build()
	File_api_fin_aggregate_service_fin_aggregate_service_proto = out.File
	file_api_fin_aggregate_service_fin_aggregate_service_proto_goTypes = nil
	file_api_fin_aggregate_service_fin_aggregate_service_proto_depIdxs = nil
}
